# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 00:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField(db_index=True)),
                ('longitude', models.FloatField(db_index=True)),
                ('is_accessible', models.BooleanField(default=False)),
                ('location_type', models.SmallIntegerField(choices=[(1, 'Restaurant'), (2, 'Office'), (3, 'Public Restroom'), (4, 'Cafe'), (5, 'School'), (6, 'Library'), (7, 'Other')])),
                ('is_family_friendly', models.BooleanField(default=False)),
                ('has_shower', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LocationRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(db_index=True, default=0)),
                ('posted_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, default='')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Location')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
